# Example completion config for chatgtp
# Currently just one set of nested keys that map to Completion.create kwargs.
# Subject to change and potentially expand to a general package config file.
completion_create:
  model: gpt-3.5-turbo
  n: 1
  temperature: 0.0
  max_tokens: 1000
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop: ;